#!/bin/bash

PROJECT_ID=$(gcloud config get-value project)
REGION="us-central1"
SVC_ACCOUNT_NAME="patient-summary"
SVC_ACCOUNT_EMAIL="$SVC_ACCOUNT_NAME@$PROJECT_ID.iam.gserviceaccount.com"
DOCKER_REPO="shiny-run"
IMAGE_NAME="shiny-run"
IMAGE_TAG="latest"
IMAGE_URI="$REGION-docker.pkg.dev/$PROJECT_ID/$DOCKER_REPO/$IMAGE_NAME:$IMAGE_TAG"
SERVICE_NAME="shiny"

echo "==================== args ====================================================================="
echo "PROJECT_ID:        " $PROJECT_ID
echo "REGION:            " $REGION
echo "SVC_ACCOUNT_NAME:  " $SVC_ACCOUNT_NAME
echo "SVC_ACCOUNT_EMAIL: " $SVC_ACCOUNT_EMAIL
echo "DOCKER_REPO:       " $DOCKER_REPO
echo "IMAGE_NAME:        " $IMAGE_NAME
echo "IMAGE_TAG:         " $IMAGE_TAG
echo "IMAGE_URI:         " $IMAGE_URI
echo "SERVICE_NAME:      " $SERVICE_NAME
echo "================================================================================================="